# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
    before_deploy:
    - R CMD INSTALL .
    - Rscript -e 'install.packages(c("pkgdown", "rorcid"))'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
      skip_cleanup: true

stages:
  - name: deploy
    if: branch = master
